### ISSUE TITLE
Latest version of Adminer (v5.4.1) is breaking the themet

### ISSUE THREAD

**Issue by melroy89** [Niyko/Hydra-Dark-Theme-for-Adminer#22]
It seems that the latest version of Adminer (v5.4.1) is breaking the theme.. Like in the header:

<img width="256" height="93" alt="Image" src="https://github.com/user-attachments/assets/65c5582d-bb16-45fd-9b51-18ea93d876a5" />

But also here the footer section of the database overview feels off:

<img width="1612" height="257" alt="Image" src="https://github.com/user-attachments/assets/9ae9a1fa-7979-416a-8401-a54d31f6ba9f" />

And finally I can not scroll through my tables in the left-panel:

Like the scroll wheel is not responding in the sidebar.. So I can't use this theme.

**Comment by Niyko** [comment]
Fixed in the v1.0.4

**Comment by melroy89** [comment]
> Fixed in the v1.0.4

1. Still see a lot of empty space here on the left (so below the menu buttons and the table names):

<img width="268" height="354" alt="Image" src="https://github.com/user-attachments/assets/a2779b4d-900c-49f7-881a-f9864e668e1c" />

2. What is happening here? all the names are combined?

<img width="262" height="63" alt="Image" src="https://github.com/user-attachments/assets/22bee0ae-58d6-4b64-b2db-6f8e47fd1ace" />

I'm running Adminer v5.4.2

**Comment by Niyko** [comment]
Did you clear the CSS cache? If yes, can you share the browser version and details that you are using.

**Comment by melroy89** [comment]
Yes,  I did clear the browser cache etc. You have a very large padding bottom on `#menu .links`..

```css
#menu .links {
	/*background-color: #7962f2;
	background-image: url('side-menu-bg.png');*/
	padding-bottom: 158px;
	background-size: 100%;
	background-position: bottom;
    border: none;
}
```

Why?

I'm using Floorp 12.14.2@151.0. But its basically Firefox. I'm using it with PostgreSQL. After clicking on a database.

**Comment by EvgeniyDoctor** [comment]
Same bug with Waterfox, adminer 5.4.2. Your theme installed for the first time.

**Comment by melroy89** [comment]
yea pretty sure its not just me indeed 😆 

EDIT: you can also fallback to https://github.com/lukashron/adminer-dark-theme in the meanwhile @EvgeniyDoctor

**Comment by Niyko** [comment]
@EvgeniyDoctor  @melroy89  This is how it looks on my device in Waterfox. It's weird the issue is not happening for me.

<img width="1230" height="1171" alt="Image" src="https://github.com/user-attachments/assets/c69ff7a7-404e-4417-8516-b2fd02606a56" />

Can you share the screen size so I can try to replicate the issue.

**Comment by EvgeniyDoctor** [comment]
@Niyko i created my own theme, so i do not have this theme anymore.
1920x1080, kde with 2 bars (top and left), so workspace is a bit smaller. And my Waterfox has vertical tabs.
