### ISSUE TITLE
Missing sql file import

### ISSUE THREAD

**Issue by rhinomikey** [Niyko/Hydra-Dark-Theme-for-Adminer#5]
![image](https://user-images.githubusercontent.com/38225083/85791593-b484c980-b6f7-11ea-8e9d-87e70d70799d.png)

This should have the file import field next to it such as: 

![image](https://user-images.githubusercontent.com/38225083/85791720-ed24a300-b6f7-11ea-985d-5fd802d46ce9.png)

        Note: the theme used in the second picture is pepa-linha-dark

This error was found on Adminer 4.7.7 running on Ubuntu Server 20.04

**Comment by Niyko** [comment]
Sorry for the late reply, this panel was accidentally hidden from view. I have fixed it. Thanks for reporting :relaxed:

**Comment by manuEbg** [comment]
This bug still appears when using the [official docker image](https://hub.docker.com/_/adminer?tab=description)

the adminer version would be 4.8.1
